services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    networks:
      - fiscalizacao

volumes:
  node_red_data:

networks:
  fiscalizacao:
    external: true




ADENDO (setup token): ec90d8429425732178421e5e6065ce1e9bc43a0de0bfbf9bcf09764bbbe23908 
